"""add drive type and position

Revision ID: 2e4d2114beb8
Revises: 3de16f1c19a2
Create Date: 2026-09-19 17:13:39.695455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e4d2114beb8"
down_revision: Union[str, Sequence[str], None] = "3de16f1c19a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "drives",
        sa.Column(
            "type",
            sa.String(length=20),
            nullable=True,
        ),
    )

    op.add_column(
        "drives",
        sa.Column(
            "position",
            sa.String(length=20),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE drives
        SET type = 'BRUSH',
            position = 'LEFT'
        WHERE id = 1
        """
    )

    op.execute(
        """
        UPDATE drives
        SET type = 'BRUSH',
            position = 'RIGHT'
        WHERE id = 2
        """
    )

    op.execute(
        """
        UPDATE drives
        SET type = 'ROLLER',
            position = NULL
        WHERE id = 3
        """
    )

    op.alter_column(
        "drives",
        "type",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drives", "position")
    op.drop_column("drives", "type")
    # ### end Alembic commands ###
