"""add winding calibrations

Revision ID: 2eccb1b32574
Revises: ed52f20a7de8
Create Date: 2026-09-23 19:35:26.013322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eccb1b32574'
down_revision: Union[str, Sequence[str], None] = 'ed52f20a7de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winding_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_profile_id', sa.Integer(), nullable=False),
    sa.Column('mode_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('belt_end_turns', sa.Float(), nullable=True),
    sa.Column('material_end_turns', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_profile_id'], ['material_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winding_calibrations')
    # ### end Alembic commands ###
