"""add mode speed settings

Revision ID: 3f78d883a8bf
Revises: 314630fb4f4d
Create Date: 2026-09-28 18:14:24.790158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f78d883a8bf'
down_revision: Union[str, Sequence[str], None] = '314630fb4f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode_speed_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_mode_id', sa.Integer(), nullable=False),
    sa.Column('belt_speed_percent', sa.Float(), nullable=False),
    sa.Column('material_speed_percent', sa.Float(), nullable=False),
    sa.Column('brush_speed_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_mode_id'], ['machine_modes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_mode_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mode_speed_settings')
    # ### end Alembic commands ###
