"""add machine calibration

Revision ID: 41f11d4560c9
Revises: 4a0700e814c0
Create Date: 2026-10-03 19:23:16.925227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f11d4560c9'
down_revision: Union[str, Sequence[str], None] = '4a0700e814c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('material_start_turns', sa.Float(), nullable=True),
    sa.Column('washing_stop_turns', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_calibrations')
    # ### end Alembic commands ###
