"""add roller core diameter to machine

Revision ID: 4a0700e814c0
Revises: 3f78d883a8bf
Create Date: 2026-09-30 20:26:47.351376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a0700e814c0"
down_revision: Union[str, Sequence[str], None] = "3f78d883a8bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "machines",
        sa.Column(
            "roller_core_diameter_mm",
            sa.Float(),
            nullable=False,
            server_default=sa.text("200.0"),
        ),
    )

    op.alter_column(
        "machines",
        "roller_core_diameter_mm",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("machines", "roller_core_diameter_mm")
    # ### end Alembic commands ###
