"""simplify winding calibration

Revision ID: c33043903584
Revises: 41f11d4560c9
Create Date: 2026-10-03 20:42:40.152505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33043903584'
down_revision: Union[str, Sequence[str], None] = '41f11d4560c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winding_calibrations', 'is_active')
    op.drop_column('winding_calibrations', 'mode_code')
    op.drop_column('winding_calibrations', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winding_calibrations', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('winding_calibrations', sa.Column('mode_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('winding_calibrations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
