"""add winding parameters

Revision ID: ed52f20a7de8
Revises: 6608e5ba5c40
Create Date: 2026-09-23 18:04:11.244328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed52f20a7de8'
down_revision: Union[str, Sequence[str], None] = '6608e5ba5c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winding_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_profile_id', sa.Integer(), nullable=False),
    sa.Column('core_diameter_mm', sa.Float(), nullable=True),
    sa.Column('material_thickness_mm', sa.Float(), nullable=True),
    sa.Column('target_speed_m_min', sa.Float(), nullable=True),
    sa.Column('calibration_turns', sa.Float(), nullable=True),
    sa.Column('calibration_final_diameter_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_profile_id'], ['material_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winding_parameters')
    # ### end Alembic commands ###
